name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint and Check

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - name: Run ShellCheck
        run: shellcheck -e SC1091,SC2034 ./.zshrc install.sh ./zsh_custom/aliases.zsh ./zsh_custom/history.zsh
